// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wedding.ContexteDB;

#nullable disable

namespace Wedding.Migrations
{
    [DbContext(typeof(WeddingContext))]
    [Migration("20241014225737_modelone")]
    partial class modelone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Wedding.Models.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInviteur")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InviteurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomInvite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomInvite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeBillets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InviteurId");

                    b.HasIndex("TableId");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("Wedding.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NbreInvitePresent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbrePlaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomTable")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatutDuJour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Table");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NbrePlaces = 10,
                            NomTable = "Table 1",
                            Statut = 0,
                            StatutDuJour = 0
                        },
                        new
                        {
                            Id = 2,
                            NbrePlaces = 8,
                            NomTable = "Table 2",
                            Statut = 1,
                            StatutDuJour = 0
                        });
                });

            modelBuilder.Entity("Wedding.Models.Invite", b =>
                {
                    b.HasOne("Wedding.Models.Invite", "Inviteur")
                        .WithMany()
                        .HasForeignKey("InviteurId");

                    b.HasOne("Wedding.Models.Table", "Table")
                        .WithMany("invites")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviteur");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Wedding.Models.Table", b =>
                {
                    b.Navigation("invites");
                });
#pragma warning restore 612, 618
        }
    }
}
