// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wedding.ContexteDB;

#nullable disable

namespace Wedding.Migrations
{
    [DbContext(typeof(WeddingContext))]
    partial class WeddingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wedding.Models.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdInviteur")
                        .HasColumnType("int");

                    b.Property<int>("IdTable")
                        .HasColumnType("int");

                    b.Property<string>("NomInvite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomInvite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QRCodeId")
                        .HasColumnType("longtext");

                    b.Property<string>("TypeBillets")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdInviteur");

                    b.HasIndex("IdTable");

                    b.ToTable("Invite");
                });

            modelBuilder.Entity("Wedding.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NbreInvitePresent")
                        .HasColumnType("int");

                    b.Property<int>("NbrePlaces")
                        .HasColumnType("int");

                    b.Property<string>("NomTable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NombreInvites")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("StatutDuJour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("Wedding.Models.Invite", b =>
                {
                    b.HasOne("Wedding.Models.Invite", "Inviteur")
                        .WithMany()
                        .HasForeignKey("IdInviteur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wedding.Models.Table", "Table")
                        .WithMany("Invites")
                        .HasForeignKey("IdTable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviteur");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Wedding.Models.Table", b =>
                {
                    b.Navigation("Invites");
                });
#pragma warning restore 612, 618
        }
    }
}
